FROM quay.io/minio/minio:latest

EXPOSE 9000 9001

ENV MINIO_ROOT_USER=minioadmin
ENV MINIO_ROOT_PASSWORD=minioadmin

CMD ["server", "/data", "--address", "0.0.0.0:9000", "--console-address", ":9001"]
